metadataId: 28c28e3a-d88f-4a34-8c60-5efe6d56a44d
ogc_feature_api: https://kos-pygeoapi.atkv3-dev.kartverket.cloud/collections
output_directory: arealanalyse
product_slug: arealanalyse
updated: 2025-11-26
